/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "gstreamer-1.0"

#define GSTCONFIG_BUILT_WITH_MSVC 0

#define GST_API_EXPORT extern __attribute__ ((visibility ("default")))

#define GST_API_VERSION "1.0"

#define GST_DATADIR "/usr/local/share"

#undef GST_DISABLE_OPTION_PARSING

#define GST_ENABLE_EXTRA_CHECKS

#define GST_LEVEL_DEFAULT GST_LEVEL_NONE

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "GStreamer source release"

#define GST_PACKAGE_ORIGIN "Unknown package origin"

#define GST_PACKAGE_RELEASE_DATETIME "2022-06-15"

#define GST_PLUGIN_SCANNER_INSTALLED "/usr/local/libexec/gstreamer-1.0/gst-plugin-scanner"

/* libexecdir path component, used to find plugin-scanner on relocatable builds */
#define GST_PLUGIN_SCANNER_SUBDIR "libexec"

/* plugin directory path component, used to find plugins on relocatable builds */
#define GST_PLUGIN_SUBDIR "media/plugins"

#define GST_PTP_HELPER_INSTALLED "/usr/local/libexec/gstreamer-1.0/gst-ptp-helper"

#define HAVE_ALARM 1

#define HAVE_CLOCK_GETTIME 1

#define HAVE_CLOCK_NANOSLEEP 1

#ifdef __LP64__
#define HAVE_CPU_AARCH64 1
#else
#define HAVE_CPU_ARM 1
#endif

#define HAVE_DECL_LOCALTIME_R 1

#define HAVE_DECL_STRDUP 1

#define HAVE_DECL_STRSIGNAL 1

#define HAVE_DLADDR

#define HAVE_DLFCN_H 1

#define HAVE_FORK 1

#define HAVE_FSEEKO 1

#define HAVE_FTELLO 1

#define HAVE_FUTEX 1

#define HAVE_GETLINE 1

#define HAVE_GETPAGESIZE 1

#define HAVE_GETPID 1

#define HAVE_GETRUSAGE 1

#define HAVE_GETTIMEOFDAY 1

#undef HAVE_GMP

#define HAVE_GMTIME_R 1

#undef HAVE_GSL

#define HAVE_INTTYPES_H 1

#define HAVE_LOCALTIME_R 1

#define HAVE_LONG_LONG 1

#define HAVE_MEMORY_H 1

#define HAVE_MKSTEMP 1

#define HAVE_MONOTONIC_CLOCK 1

#define HAVE_POLL 1

#define HAVE_POLL_H 1

#define HAVE_POSIX_TIMERS 1

#define HAVE_PPOLL 1

#define HAVE_PSELECT 1

#define HAVE_PTHREAD_CONDATTR_SETCLOCK 1

#define HAVE_SIGACTION 1

#define HAVE_STDINT_H 1

#define HAVE_STDIO_EXT_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_STRNLEN 1

#define HAVE_SYS_PARAM_H 1

#define HAVE_POLL_H 1

#define HAVE_SYS_PRCTL_H 1

#define HAVE_SYS_RESOURCE_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TIMES_H 1

#define HAVE_SYS_TIME_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_SYS_UIO_H 1

#define HAVE_SYS_UTSNAME_H 1

#define HAVE_SYS_WAIT_H 1

#define HAVE_TM_GMTOFF 1

#define HAVE_UCONTEXT_H 1

#ifdef __LP64__
#define HAVE_UINT128_T 1
#endif

#define HAVE_UNISTD_H 1

#ifdef __LP64__
#define LIBDIR "/system/lib64"
#else
#define LIBDIR "/system/lib"
#endif

#define LOCALEDIR "/usr/local/share/locale"

#define MEMORY_ALIGNMENT_MALLOC 1

#define PACKAGE "gstreamer"

#define PACKAGE_BUGREPORT "https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/new"

#define PACKAGE_NAME "GStreamer"

#define PACKAGE_STRING "GStreamer 1.20.3"

#define PACKAGE_TARNAME "gstreamer"

#define PACKAGE_URL ""

#define PACKAGE_VERSION "1.20.3"

#ifdef __LP64__
#define PLUGINDIR "/system/lib64/media/plugins"
#else
#define PLUGINDIR "/system/lib/media/plugins"
#endif

#ifdef __LP64__
#define TARGET_CPU "aarch64"
#else
#define TARGET_CPU "arm"
#endif

#undef USE_POISONING

#define VERSION "1.20.3"

