/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define AUDIORESAMPLE_FORMAT_AUTO

#define DEFAULT_AUDIOSINK "autoaudiosink"

#define DEFAULT_VIDEOSINK "autovideosink"

#define DISABLE_ORC 1

#define GETTEXT_PACKAGE "gst-plugins-base-1.0"

#ifdef __LP64__
#define GIO_LIBDIR "/system/lib64"
#else
#define GIO_LIBDIR "/system/lib"
#endif

#ifdef __LP64__
#define GIO_MODULE_DIR "/system/lib64/gio/modules"
#else
#define GIO_MODULE_DIR "/system/lib/gio/modules"
#endif

#define GIO_PREFIX "/usr/local"

#define GST_API_EXPORT extern __attribute__ ((visibility ("default")))

#define GST_API_VERSION "1.0"

#define GST_DATADIR "/usr/local/share"

#define GST_INSTALL_PLUGINS_HELPER "/usr/local/libexec/gst-install-plugins-helper"

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "GStreamer Base Plug-ins source release"

#define GST_PACKAGE_ORIGIN "Unknown package origin"

#define GST_PACKAGE_RELEASE_DATETIME "2022-06-15"

#ifdef __LP64__
#define HAVE_CPU_AARCH64 1
#else
#define HAVE_CPU_ARM 1
#endif

#define HAVE_DCGETTEXT 1

#define HAVE_DLFCN_H 1

#define HAVE_EMMINTRIN_H 1

#define HAVE_GIO_UNIX_2_0

#define HAVE_GMTIME_R 1

#define HAVE_INTTYPES_H 1

#undef HAVE_ISO_CODES

#define HAVE_LINUX_DMA_BUF_H 1

#define HAVE_LINUX_TCP_INFO

#define HAVE_LOCALTIME_R 1

#define HAVE_LOG2 1

#define HAVE_LRINTF 1

#define HAVE_MEMORY_H 1

#define HAVE_MMAP 1

#define HAVE_NETINET_IN_H 1

#define HAVE_NETINET_TCP_H 1

#undef HAVE_OGG

#define HAVE_SMMINTRIN_H 1

#define HAVE_STDINT_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_SYS_WAIT_H 1

#define HAVE_UNISTD_H 1

#undef HAVE_X11

#define HAVE_XMMINTRIN_H 1

#define HAVE_ZLIB

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE "gst-plugins-base"

#define PACKAGE_VERSION "1.20.3"

#define SIZEOF_CHAR 1

#define SIZEOF_INT 4

#define SIZEOF_LONG 8

#define SIZEOF_SHORT 2

#define SIZEOF_VOIDP 8

#ifdef __LP64__
#define TARGET_CPU "aarch64"
#else
#define TARGET_CPU "arm"
#endif

#define VERSION "1.20.3"

