/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEFAULT_VIDEOSRC "videotestsrc"

#define DISABLE_ORC 1

#define GETTEXT_PACKAGE "gst-plugins-bad-1.0"

#define GST_API_EXPORT extern __attribute__ ((visibility ("default")))

#define GST_API_VERSION "1.0"

#define GST_ENABLE_EXTRA_CHECKS

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "GStreamer Bad Plug-ins source release"

#define GST_PACKAGE_ORIGIN "Unknown package origin"

#define GST_PACKAGE_RELEASE_DATETIME "2022-06-15"

#define HAVE_DCGETTEXT 1

#define HAVE_DLFCN_H 1

#define HAVE_FCNTL_H 1

#define HAVE_GETPAGESIZE 1

#define HAVE_GETRUSAGE 1

#define HAVE_GMTIME_R 1

#define HAVE_INTTYPES_H 1

#define HAVE_MAKEDEV_IN_MKDEV 0

#define HAVE_MAKEDEV_IN_SYSMACROS 1

#define HAVE_MAKEDEV_IN_TYPES 0

#define HAVE_MEMFD_CREATE 1

#define HAVE_MEMORY_H 1

#define HAVE_MMAP 1

#define HAVE_NETINET_IN_H 1

#define HAVE_NETINET_IP_H 1

#define HAVE_NETINET_TCP_H 1

#define HAVE_PIPE2 1

#define HAVE_PTHREAD_H 1

#define HAVE_STDINT_H 1

#define HAVE_STDLIB_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_PARAM_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TIME_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_SYS_UTSNAME_H 1

#define HAVE_UNISTD_H 1

#ifdef __LP64__
#define LIBDIR "/system/lib64"
#else
#define LIBDIR "/system/lib"
#endif

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE "gst-plugins-bad"

#define PACKAGE_BUGREPORT "https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/new"

#define PACKAGE_NAME "GStreamer Bad Plug-ins"

#define PACKAGE_VERSION "1.20.3"

#define SIZEOF_CHAR 1

#define SIZEOF_INT 4

#define SIZEOF_LONG 8

#define SIZEOF_SHORT 2

#define SIZEOF_VOIDP 8

#define VERSION "1.20.3"

