/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GST_PACKAGE_NAME "GStreamer FFMPEG Plug-ins source release"

#define GST_PACKAGE_ORIGIN "Unknown package origin"

#define GST_PACKAGE_RELEASE_DATETIME "2022-06-15"

#define HAVE_UNISTD_H 1

#define LIBAV_SOURCE "system install"

#define PACKAGE "gst-libav"

#define PACKAGE_VERSION "1.20.3"

