/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DISABLE_ORC 1

#define GETTEXT_PACKAGE "gst-plugins-good-1.0"

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "GStreamer Good Plug-ins source release"

#define GST_PACKAGE_ORIGIN "Unknown package origin"

#define GST_PACKAGE_RELEASE_DATETIME "2022-06-15"

#define GST_V4L2_ENABLE_PROBE

#define HAVE_ASINH 1

#undef HAVE_BZ2

#define HAVE_CLOCK_GETTIME 1

#define HAVE_COSH 1

#undef HAVE_CPU_X86_64

#define HAVE_DCGETTEXT 1

#define HAVE_DLFCN_H 1

#define HAVE_FCNTL_H 1

#define HAVE_GCC_ASM

#define HAVE_GETPAGESIZE 1

#define HAVE_GMTIME_R 1

#define HAVE_GST_V4L2

#undef HAVE_GUDEV

#define HAVE_INTTYPES_H 1

#undef HAVE_IOS

#define HAVE_ISINF 1

#undef HAVE_LIBV4L2

#define HAVE_MEMORY_H 1

#define HAVE_MMAP 1

/* OSS includes are in sys/ */
#define HAVE_OSS_INCLUDE_IN_SYS 1

#define HAVE_RTLD_NOLOAD

#define HAVE_SINH 1

#define HAVE_STDINT_H 1

#define HAVE_STDLIB_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_IOCTL_H 1

#define HAVE_SYS_PARAM_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TIME_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_UNISTD_H 1

#define HAVE_ZLIB

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE "gst-plugins-good"

#define PACKAGE_VERSION "1.20.3"

#define SIZEOF_CHAR 1

#define SIZEOF_INT 4

#define SIZEOF_LONG 8

#define SIZEOF_OFF_T 8

#define SIZEOF_SHORT 2

#define SIZEOF_VOIDP 8

#define VERSION "1.20.3"

